language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "fs7-final-project"
    token:
      secure: "YE6gmS5vhblCe/65htC7AEWO62a6Ck/MCB8yiALYdsncZWU6KmU11sEkMloIaeisFgKCuocWXkulbpeUNmbqj+8n+u6Bs5oeI4mxTNQjX5onM26GMxGQebYv6kAxnfF/Z5yGYRzJFCzqjd4NFFlsA1VDg+H53YB1Ld7vlBkvjznQy1ViZuMV2n0mF4+HtT/70/6Q1a98rUlhUkshmNCiqKiv8P4qo4n7F6P67g+W5UWUrn4z2sEt6hSLDte6HvLeMY2r+E3EXd2+K8DSFeJHVrIgGmlvVLUct1MQC7/9Z57Aqizw0NYgEm/hJiFXEZoxu4nzqe6Ja52EAZTFuuRHuLvYxWvGT4hMC3UbSJKI7EE89K3Ch6IeRW685d7P/F11vSZFeA8kW2UTzTe78O9ifOTQGfG3XgjR8/lVEPnzpdHChcV3MuyS0J3vsqpqXdbIL5qrHfj1aK7GOMf97Sb4tzMGNUoBzVqUGIxGtDZXEtxissBpRLILJKe1HpqwpJ41J/xyzO/Mez48+QKuW+8LwknjbWJ4gVuMzkY6x0BvdmMv69glFnqSw+iT3bvDq/vm1IzCVMMmk/plv04PyNInDlnEknKQVmqgFiq3BBM7sluCTxRMNBM3I1dx//Z+VXa0HieEXsA/oUSVcdh1d4MKgNhM0ref47RFA0y3/KIobDc="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'