dist: trusty
language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: fs7-final-project
    token:
      secure: j8IEAohThlp2+Efy5hVLRzUv2/D4caJ4QmI83f/9JpYBz3Y8MfM/Tj9Yp13ynTnmNgK2gaRDOrmlV+nVWZtrf6dq+KWTIgeVWTXbzHAPMNMNJs0yXpjiFY6Ptm5tzI+52Es1kRyr+SHR1NY5o4F6fBBBoqBZ2PVn//V/9N+U/AOt2gb0TIPFKUA/yaKqx9ShZWUonsiaxiWwnfDVoMDcQsEQSrSMGPEvapzRsDvhyosHiyJrk7Xs5n/mab3gIiY1dKmcecNJIUfZIRps1+sGxv+xoavXiiSS2TPtiS294Do699Gyl2HkP+FtSM7M7p/5rvboY+zvj5p8XSbbwi4B0rjkVsmzQFMXPJJ+lW4b/IS7yby3kwFp6ugGaUriIRwqK04VruuVDy545xo3c7Gc3GtMjlpNwbbhWdCunZOGtopvsnaJMh51zgACEnR7pfUVkLp8TMV4Tc/NeIX+6QQrhRvkH6FfzzLo3FmL2A1JMTfLereTca6OXq/TrtNB957KVyK9OyWIFWSbJprp+RCDcRWrG9ecgyNANirxBvqfUH1IXPfUUyDd+LAdErqSJyHb27GBLt1lx6YTV7Z9UOMgtjq/gbdq2KQnazQSf8AaGDC4spFF2eCEWGpBdwD+AsH1XQ0qHWsV16OPWZ7ryxhLg9JiAdYFstJoQgg0qy72Mk8=
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fs7-final-project
