language: java

addons:
  sonarcloud:
    organization: "fs7-final-project"
    token:
      secure: "tsyNcsVwh+9vQSIq2f7Ih1g0eWqqo5WtWZeglWA6ErRWfwZ9rjKFNK2UaHtHF7IhZ3bKOV7ah8i2mvyfwiSaUoDpy3YchwQ+tRIUalPQ/SYlZt5G0eSeaUp7ELfBR4s8A7T2acaq7SSXCahaB7xFlvyo9TZpX1BYgFmCHALOxX/+m6xUnqtglI3ekVErSacIdHp1bfVFyiwNwIDMnXSDhoPZ1yEAFcD4ZsReL2NG1pzq0AkX4BizwaJWXohKBY//o86AXUKpe3lmx2vc7eFrzvxj/xuzUR467yk38n+ArX9HevwnQWN/OuKiq8ZwU9TWXEH+loaewDdka78Y8cTFxMIb3kyAejvo5OeOwOVOnkYI7LZoDA5r4gtj9zwHtQ2sjKZhW7HnZmz6/CXlTvHz0Al8/GrDgbLshRDztr8DLHPHupoimQ1LSbTn043Kjr2vf9R9euHEv0v5/vVCxmifHqGuwzQXmtZiSQaEcdgymXq/++EAqGhhb6WxXx9BrFpqfc9bSFw7qQAnp7GqkvLBd4QP0eCD9afOl54qc4nY64hA2VMcxzSdNexMrwynByotETdKgbsVwOy8hQbANIg6Dh/XZ1UCduXFRmweyqIV+/3q+YCfXZyPbKUmBFFlOOJlv3csrk6PWKBH43e712XJyZfrRNFPtY0U5rfiPfxdgyY="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fs7-final-project