server:
  port: 9000

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

spring:
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:fp_eshop_db
    username: fs7
    password:

    data: classpath*:db/data/*.sql
    schema: classpath*:db/schema/*.sql

  h2:
    console:
      enabled: true
      path: /console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true


---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/fp_eshop_db?createDatabaseIfNotExist=true
    username: postgres
    password: postgres

---