INSERT INTO PROPERTIES (ID, NAME, DESCRIPTION) VALUES (1, 'Розмір', NULL);

INSERT INTO PROPERTY_VALUES (ID, NAME, DESCRIPTION, PROPERTY_ID) VALUES (1, '15', NULL, 1);
INSERT INTO PROPERTY_VALUES (ID, NAME, DESCRIPTION, PROPERTY_ID) VALUES (2, '17', NULL, 1);
INSERT INTO PROPERTY_VALUES (ID, NAME, DESCRIPTION, PROPERTY_ID) VALUES (3, '18', NULL, 1);

INSERT INTO ADDRESSES (ID, ADDRESS_LINE, CITY, COUNTRY, STATE, STREET, ZIP_CODE)
VALUES (1, '1004 Україна Черкаська область смт.Верхнячка Іліїнська 4 1', NULL, NULL, NULL, NULL, NULL);

INSERT INTO USERS (ID, ADDRESS_ID, BIRTH_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME
           ,GENDER, IS_ACTIVE, LAST_NAME, LOGIN_NAME, LOGIN_PASSWORD, MIDDLE_NAME, PHONE_NUMBER
           ,ROLE, VERIFICATION_CODE)
VALUES (1, 1, '1987-10-23', 'ivanov@gmail.com', 1, 'Іван', 'M', 1, 'Іванов', 'ivanov', 'ivanov123',
        'Семенович', '+380502346578', 'A', '2345');

INSERT INTO ADDRESSES (ID, ADDRESS_LINE, CITY, COUNTRY, STATE, STREET, ZIP_CODE)
VALUES (2, 'Україна, м.Київ, Шевченківський, Бажана буд.100, кв.105, під.3, пов.4', NULL, NULL, NULL, NULL, NULL);

INSERT INTO USERS (ID, ADDRESS_ID, BIRTH_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME
                  ,GENDER, IS_ACTIVE, LAST_NAME, LOGIN_NAME, LOGIN_PASSWORD, MIDDLE_NAME, PHONE_NUMBER
                  ,ROLE, VERIFICATION_CODE)
VALUES (2, 2, '1998-01-22', 'petrov@gmail.com', 1, 'Петро', 'M', 1, 'Петров', 'petrov', 'petrov123', 'Іванович',
        '+380508765434', 'A', '0987');

INSERT INTO ADDRESSES (ID, ADDRESS_LINE, CITY, COUNTRY, STATE, STREET, ZIP_CODE)
VALUES (3, 'Україна, м.Київ, Голосіївський, 40-річчя Перемоги буд.23, корп.а, кв.45, під.2, пов.3', NULL, NULL, NULL, NULL, NULL);

INSERT INTO USERS (ID, ADDRESS_ID, BIRTH_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME
                  ,GENDER, IS_ACTIVE, LAST_NAME, LOGIN_NAME, LOGIN_PASSWORD, MIDDLE_NAME, PHONE_NUMBER
                  ,ROLE, VERIFICATION_CODE)
VALUES (3, 3, '1977-09-03', 'semenov@gmail.com', 1, 'Віктор', 'M', 1, 'Семенов', 'semenov', 'semenov123',
        'Олексійович', '+380672346578', 'A', '0023');

INSERT INTO ADDRESSES (ID, ADDRESS_LINE, CITY, COUNTRY, STATE, STREET, ZIP_CODE)
VALUES (4, 'Україна, м.Київ, Печерський, бул. Дружби Народів буд.11, кв.4', NULL, NULL, NULL, NULL, NULL);

INSERT INTO USERS (ID, ADDRESS_ID, BIRTH_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME
                  ,GENDER, IS_ACTIVE, LAST_NAME, LOGIN_NAME, LOGIN_PASSWORD, MIDDLE_NAME, PHONE_NUMBER
                  ,ROLE, VERIFICATION_CODE)
VALUES (4, 4, '2000-01-12', 'solomon@gmail.com', 1, 'Жанна', 'F', 1, 'Соломонівна', 'solomonivna', 'zhanna123',
        'Василівна', '+380507776543', 'A', '6654');

INSERT INTO ADDRESSES (ID, ADDRESS_LINE, CITY, COUNTRY, STATE, STREET, ZIP_CODE)
VALUES (5, 'Україна, Деснянський р-н, м.Київ, кв.23', NULL, NULL, NULL, NULL, NULL);

INSERT INTO USERS (ID, ADDRESS_ID, BIRTH_DATE, EMAIL, EMAIL_VERIFIED, FIRST_NAME
                  ,GENDER, IS_ACTIVE, LAST_NAME, LOGIN_NAME, LOGIN_PASSWORD, MIDDLE_NAME, PHONE_NUMBER
                  ,ROLE, VERIFICATION_CODE)
VALUES (5, 5, '1998-12-01', 'kolyada@gmail.com', 1, 'Степан', 'M', 1, 'Коляда', 'kolyada', 'kolyada123',
        'Афанасович', '+380509987654', 'C', '1123');
