INSERT INTO PROPERTIES (ID, NAME, DESCRIPTION) VALUES (1, 'Розмір', NULL);

INSERT INTO PROPERTY_VALUES (ID, NAME, DESCRIPTION, PROPERTY_ID) VALUES (1, '15', NULL, 1);
INSERT INTO PROPERTY_VALUES (ID, NAME, DESCRIPTION, PROPERTY_ID) VALUES (2, '17', NULL, 1);
INSERT INTO PROPERTY_VALUES (ID, NAME, DESCRIPTION, PROPERTY_ID) VALUES (3, '18', NULL, 1);
