const CategoryActionTypes = {
  FETCH_CATEGORY_START: 'FETCH_CATEGORY_START',
  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE'
};

export default CategoryActionTypes;
